name: Linux hardware test

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Install necessary tools
      run: |
        rm -rf /etc/apt/trusted.gpg
        sudo apt -y update
        sudo apt -y install cmake libboost-all-dev
        sudo apt -y install python3-pip python3-setuptools

    - name: Build it
      run: |
        git submodule update --init --recursive
        mkdir build
        cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel --config Debug

    - name: Run tests
      run: |
        cd build
        ./test-message
        ls -ls /dev/ttyUSB*
        for device in /dev/ttyUSB*; do $PWD/test-device --conn serial:$device:115200; done
